### ISSUE TITLE
Using athena with crystal 1.5 receives errors during compile.

### ISSUE THREAD

**Issue by marvfinsy** [athena-framework/athena#190]
Intel Mac
Using crystal 1.5.0
Using Athena 0.17.0
Following your Getting Started example i attempted to build.
I received the 2 Warnings/Errors:

In /usr/local/Cellar/crystal/1.5.0/share/crystal/src/json/any.cr:138:11

 138 | def dig(index_or_key : String | Int, *subkeys) : JSON::Any
               ^-----------
Warning: positional parameter 'index_or_key' corresponds to parameter 'key_or_index' of the overridden method Athena::Serializer::Any#dig(key_or_index : String | Int, *keys), which has a different name and may affect named argument passing

In /usr/local/Cellar/crystal/1.5.0/share/crystal/src/yaml/any.cr:138:11

 138 | def dig(index_or_key, *subkeys) : YAML::Any
               ^-----------
Warning: positional parameter 'index_or_key' corresponds to parameter 'key_or_index' of the overridden method Athena::Serializer::Any#dig(key_or_index : String | Int, *keys), which has a different name and may affect named argument passing

**Comment by Blacksmoke16** [comment]
They're just warnings so you can safely ignore them. Was fixed in https://github.com/athena-framework/athena/pull/188.

**Comment by Blacksmoke16** [comment]
@marvfinsy  As a heads up I ended up deciding the breaking changes are unlikely to affect really anyone at all, so will be getting a patch release out for all the effected components tomorrow. Once those are out can just `shards update` and should be good to go.
