### ISSUE TITLE
Feature request: Add a way to register custom error handlers based on error codes

### ISSUE THREAD

**Issue by analogsalad** [athena-framework/athena#203]
The feature request is for `athena-routing` and the use-case is using `athena-routing` as a standalone HTTP router.

A simple example of how I use the router:

```crystal
router = ART::RoutingHandler.new

router.add "users", ART::Route("/users", methods: "get") do |ctx|
  users_controller.render(ctx)
end
```

A sinatra-esque way to add error handling might look like in pseudo-code:

```
Exceptions::NotFound do 
  error_handler.render_not_found
end
```

If this type of syntax would not be viable, adding an instance variable to the routing handler would be also a fine solution. This way, the user can define a custom error handler and place it after the router in the handler stack, and there check for exceptions and react to them based on their type.

**Comment by Blacksmoke16** [comment]
I'm thinking the most flexible solution would be to augment the route handler to optionally bubble up exceptions such that another `HTTP::Handler` would be able to rescue these in order to customize how to respond. This way the routing component can stay purely routing. E.g. something like:

```cr
class ErrorHandler
  include HTTP::Handler

  def call(context)
    # This handler would be directly before `ART::RoutingHandler`
    call_next context
  rescue ex
    # Do something based on the ex, such as rendering the appropriate template, mapping ART exceptions to their code etc
  end
end
```

Thoughts?

**Comment by analogsalad** [comment]
That'd be fine as I would be able to catch the exceptions and deal with them with another `HTTP::Handler`.
