### ISSUE TITLE
`ARTA::Route` annotation did not register routes when prefixing it without a key parameter.

### ISSUE THREAD

**Issue by tamdaz** [athena-framework/athena#481]
### With the key/value pair in the `ARTA::Route` annotation.
```crystal
@[ARTA::Route(path: "/api")] # <==
class ClasseController < ATH::Controller
  @[ARTA::Get("/classes")]
  def index : Athena::Framework::Response
    # ...
  end
end
```

Paths are shown in the route list (those prefixed with `/api`).

![image](https://github.com/user-attachments/assets/65c7ed64-919b-4e57-abae-fbe65807cc69)

### With only the value in the `ARTA::Route` annotation.

```crystal
@[ARTA::Route("/api")] # without specifing the "path" key.
class ClasseController < ATH::Controller
  @[ARTA::Get("/classes")]
  def index : Athena::Framework::Response
    # ...
  end
end
```

However, routes concerning classes are not prefixed by `/api`.

![image](https://github.com/user-attachments/assets/0c5e6ca8-4d04-4612-8c32-0823c3fcce76)

Without specifying a "path" key in this annotation could it be a problem?

**Comment by Blacksmoke16** [comment]
Yea seems the code is only looking for `path` by name explicitly. Don't really recall why tho. So probably would make sense to make it consistent with how it works on a controller action within the class.

**Comment by tamdaz** [comment]
From my analysis, the [`Athena::Framework::Controller`](https://github.com/athena-framework/athena/blob/master/src/components/framework/src/controller.cr#L146) controller contains a macro that checks if the method exists or not in the `CONTROLLER_ACTION_METHODS`.
Then, the [`Athena::Framework::Routing::AnnotationRouteLoader`](https://github.com/athena-framework/athena/blob/master/src/components/framework/src/ext/routing/annotation_route_loader.cr#L22) controller contains a macro that allows to load annotations on all classes and methods; if my analyses are clear.

In my memory, when I was using Kemal and there were no annotations, I created some for my controllers.
```crystal
{% if controller.annotation(Route::Group) %}
  # Get the path by using "args[0]"
  {{ path_group = controller.annotation(Route::Group).args[0] }}
{% else %}
  {{ path_group = "" }}
{% end %}
```
